


spring:
  application:
    name: api-gateway
server:
  port: 8765
  
    
debug: true

  

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: info
    
  file: C:/Apigee/micro-services/Work/Azure/logs/api-gateway/plm-api-gateway-ms.log