server:
  port: 9292


debug: true

  

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: info
    
  file: C:/Apigee/micro-services/Work/Azure/logs/webportal/plm-webportal-ms.log
  
  
  
 
  #${HOME}\site\wwwroot\pologs\web-portal.log